[versions]
agp = "8.2.2"
kotlin = "1.9.20"  # Понизили до совместимой версии
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version = "1.5.4" }
androidx-material3 = { module = "androidx.compose.material3:material3", version = "1.1.2" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.5" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }